var digits = {
  "deckId": "digits",
  "deckTitle": "Sanskrit Digits",
  "landingPage": "index.html",
  "initialScript": "Unicode",
  "scriptCanBeSet": false,
  "mainPartFontSize": "32pt",
  "showAudioWithLocalNameQuiz": false,
  "showAudioWithUrNameQuiz": false,
  "showAudioWithUrnameQuizAnswers": true,
  "showDescription": false,
  "groupCanBeSet": true,
  "groupDisplay": "Group",
  "trainingModes": [
    "Review",
    "Urname",
    "LocalName"
  ],
  "pluralSubjectName": "Digits",
  "copyrightNotice": "Audio excerpted from Pravesha © Samskrita Bharati 2014",
  "numChoices": 10,
  "trainModeDisplay": {
    "Review": "Review",
    "Urname": "Devanagari",
    "LocalName": "ISO 15919 (Latin)",
  },
  "scriptHeading": "Sanskrit Script",
  "allSubjects": [
    {
      "subjectId": 1,
      "audioUrl": "decks/digits/assets/audio/00000001.mp3",
      "unicode": "१",
      "latin": "",
      "localNames": ["1"],
      "description": "",
    },
    {
      "subjectId": 2,
      "audioUrl": "decks/digits/assets/audio/00000002.mp3",
      "unicode": "२",
      "latin": "",
      "localNames": ["2"],
      "description": "",
    },
    {
      "subjectId": 3,
      "audioUrl": "decks/digits/assets/audio/00000003.mp3",
      "unicode": "३",
      "latin": "",
      "localNames": ["3"],
      "description": "",
    },
    {
      "subjectId": 4,
      "audioUrl": "decks/digits/assets/audio/00000004.mp3",
      "unicode": "४",
      "latin": "",
      "localNames": ["4"],
      "description": "",
    },
    {
      "subjectId": 5,
      "audioUrl": "decks/digits/assets/audio/00000005.mp3",
      "unicode": "५",
      "latin": "",
      "localNames": ["5"],
      "description": "",
    },
    {
      "subjectId": 6,
      "audioUrl": "decks/digits/assets/audio/00000006.mp3",
      "unicode": "६",
      "latin": "",
      "localNames": ["6"],
      "description": "",
    },
    {
      "subjectId": 7,
      "audioUrl": "decks/digits/assets/audio/00000007.mp3",
      "unicode": "७",
      "latin": "",
      "localNames": ["7"],
      "description": "",
    },
    {
      "subjectId": 8,
      "audioUrl": "decks/digits/assets/audio/00000008.mp3",
      "unicode": "८",
      "latin": "",
      "localNames": ["8"],
      "description": "",
    },
    {
      "subjectId": 9,
      "audioUrl": "decks/digits/assets/audio/00000009.mp3",
      "unicode": "९",
      "latin": "",
      "localNames": ["9"],
      "description": "",
    },
  ]
}

var app = Elm.Main.init({
  node: document.getElementById('elm'),
  flags: digits
});