var numbers = {
  "deckId": "numbers",
  "deckTitle": "Sanskrit Numbers",
  "landingPage": "index.html",
  "initialScript": "Unicode",
  "scriptCanBeSet": true,
  "autoPlayCanBeSet": true,
  "mainPartFontSize": "32pt",
  "showAudioWithUrNameQuiz": false,
  "showAudioWithLocalNameQuiz": true,
  "showDescription": false,
  "groupCanBeSet": true,
  "groupDisplay": "Group",
  "trainingModes": [
    "Review",
    "Urname",
    "LocalName"
  ],
  "pluralSubjectName": "Numbers",
  "copyrightNotice": "",
  "numChoices": 4,
  "trainModeDisplay": {
    "Review": "Review",
    "Urname": "Sanskrit",
    "LocalName": "English",
  },
  "scriptHeading": "Sanskrit Script",
  "allSubjects": [
    {
      "subjectId": 1,
      "audioUrl": "decks/numbers/assets/audio/00000001.mp3",
      "unicode": "एकम्",
      "latin": "ēkam",
      "localNames": ["one", "1"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 2,
      "audioUrl": "decks/numbers/assets/audio/00000002.mp3",
      "unicode": "द्वे",
      "latin": "dvē",
      "localNames": ["two", "2"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 3,
      "audioUrl": "decks/numbers/assets/audio/00000003.mp3",
      "unicode": "त्रीणि",
      "latin": "trīṇi",
      "localNames": ["three", "3"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 4,
      "audioUrl": "decks/numbers/assets/audio/00000004.mp3",
      "unicode": "चत्वारि",
      "latin": "catvāri",
      "localNames": ["four", "4"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 5,
      "audioUrl": "decks/numbers/assets/audio/00000005.mp3",
      "unicode": "पञ्च",
      "latin": "pañca",
      "localNames": ["five", "5"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 6,
      "audioUrl": "decks/numbers/assets/audio/00000006.mp3",
      "unicode": "षट्",
      "latin": "ṣaṭ",
      "localNames": ["six", "6"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 7,
      "audioUrl": "decks/numbers/assets/audio/00000007.mp3",
      "unicode": "सप्त",
      "latin": "sapta",
      "localNames": ["seven", "7"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 8,
      "audioUrl": "decks/numbers/assets/audio/00000008.mp3",
      "unicode": "अष्ट",
      "latin": "aṣṭa",
      "localNames": ["eight", "8"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 9,
      "audioUrl": "decks/numbers/assets/audio/00000009.mp3",
      "unicode": "नव",
      "latin": "nava",
      "localNames": ["nine", "9"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 10,
      "audioUrl": "decks/numbers/assets/audio/00000010.mp3",
      "unicode": "दश",
      "latin": "daśa",
      "localNames": ["ten", "10"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 11,
      "audioUrl": "decks/numbers/assets/audio/00000011.mp3",
      "unicode": "एकादश",
      "latin": "ēkādaśa",
      "localNames": ["eleven", "11"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 12,
      "audioUrl": "decks/numbers/assets/audio/00000012.mp3",
      "unicode": "द्वादश",
      "latin": "dvādaśa",
      "localNames": ["twelve", "12"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 13,
      "audioUrl": "decks/numbers/assets/audio/00000013.mp3",
      "unicode": "त्रयॊदश",
      "latin": "trayodaśa",
      "localNames": ["thirteen", "13"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 14,
      "audioUrl": "decks/numbers/assets/audio/00000014.mp3",
      "unicode": "चतुर्दश",
      "latin": "caturdaśa",
      "localNames": ["fourteen", "14"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 15,
      "audioUrl": "decks/numbers/assets/audio/00000015.mp3",
      "unicode": "पञ्चदश",
      "latin": "pañcadaśa",
      "localNames": ["fifteen", "15"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 16,
      "audioUrl": "decks/numbers/assets/audio/00000016.mp3",
      "unicode": "षोडश",
      "latin": "ṣōḍaśa",
      "localNames": ["sixteen", "16"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 17,
      "audioUrl": "decks/numbers/assets/audio/00000017.mp3",
      "unicode": "सप्तदश",
      "latin": "saptadaśa",
      "localNames": ["seventeen", "17"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 18,
      "audioUrl": "decks/numbers/assets/audio/00000018.mp3",
      "unicode": "अष्टादश",
      "latin": "aṣṭādaśa",
      "localNames": ["eighteen", "18"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 19,
      "audioUrl": "decks/numbers/assets/audio/00000019.mp3",
      "unicode": "नवदश",
      "latin": "navadaśa",
      "localNames": ["nineteen", "19"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 20,
      "audioUrl": "decks/numbers/assets/audio/00000020-3.mp3",
      "unicode": "विंशतिः",
      "latin": "viṁśatiḥ",
      "localNames": ["twenty", "20"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 21,
      "audioUrl": "decks/numbers/assets/audio/00000021.mp3",
      "unicode": "एकविंशतिः",
      "latin": "ēkaviṁśatiḥ",
      "localNames": ["twenty-one", "21"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 22,
      "audioUrl": "decks/numbers/assets/audio/00000022.mp3",
      "unicode": "द्वाविंशतिः",
      "latin": "dvāviṁśatiḥ",
      "localNames": ["twenty-two", "22"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 23,
      "audioUrl": "decks/numbers/assets/audio/00000023.mp3",
      "unicode": "त्रयोविंशतिः",
      "latin": "trayōviṁśatiḥ",
      "localNames": ["twenty-three", "23"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 24,
      "audioUrl": "decks/numbers/assets/audio/00000024.mp3",
      "unicode": "चतुर्विंशतिः",
      "latin": "caturviṁśatiḥ",
      "localNames": ["twenty-four", "24"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 25,
      "audioUrl": "decks/numbers/assets/audio/00000025.mp3",
      "unicode": "पञ्चविंशतिः",
      "latin": "pañcaviṁśatiḥ",
      "localNames": ["twenty-five", "25"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 26,
      "audioUrl": "decks/numbers/assets/audio/00000026.mp3",
      "unicode": "षड्विंशतिः",
      "latin": "ṣaḍviṁśatiḥ",
      "localNames": ["twenty-six", "26"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 27,
      "audioUrl": "decks/numbers/assets/audio/00000027.mp3",
      "unicode": "सप्तविंशतिः",
      "latin": "saptaviṁśatiḥ",
      "localNames": ["twenty-seven", "27"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 28,
      "audioUrl": "decks/numbers/assets/audio/00000028.mp3",
      "unicode": "अष्टाविंशतिः",
      "latin": "aṣṭāviṁśatiḥ",
      "localNames": ["twenty-eight", "28"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 29,
      "audioUrl": "decks/numbers/assets/audio/00000029.mp3",
      "unicode": "नवविंशतिः",
      "latin": "navaviṁśatiḥ",
      "localNames": ["twenty-nine", "29"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 30,
      "audioUrl": "decks/numbers/assets/audio/00000030-3.mp3",
      "unicode": "त्रिंशत्",
      "latin": "triṁśat",
      "localNames": ["thirty", "30"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 31,
      "audioUrl": "decks/numbers/assets/audio/00000031.mp3",
      "unicode": "एकत्रिंशत्",
      "latin": "ēkatriṁśat",
      "localNames": ["thirty-one", "31"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 32,
      "audioUrl": "decks/numbers/assets/audio/00000032.mp3",
      "unicode": "द्वात्रिंशत्",
      "latin": "dvātriṁśat",
      "localNames": ["thirty-two", "32"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 33,
      "audioUrl": "decks/numbers/assets/audio/00000033.mp3",
      "unicode": "त्रयस्त्रिंशत्",
      "latin": "trayastriṁśat",
      "localNames": ["thirty-three", "33"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 34,
      "audioUrl": "decks/numbers/assets/audio/00000034.mp3",
      "unicode": "चतुस्त्रिंशत्",
      "latin": "catustriṁśat",
      "localNames": ["thirty-four", "34"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 35,
      "audioUrl": "decks/numbers/assets/audio/00000035.mp3",
      "unicode": "पञ्चत्रिंशत्",
      "latin": "pañcatriṁśat",
      "localNames": ["thirty-five", "35"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 36,
      "audioUrl": "decks/numbers/assets/audio/00000036.mp3",
      "unicode": "षट्त्रिंशत्",
      "latin": "ṣaṭtriṁśat",
      "localNames": ["thirty-six", "36"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 37,
      "audioUrl": "decks/numbers/assets/audio/00000037.mp3",
      "unicode": "सप्तत्रिंशत्",
      "latin": "saptatriṁśat",
      "localNames": ["thirty-seven", "37"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 38,
      "audioUrl": "decks/numbers/assets/audio/00000038.mp3",
      "unicode": "अष्टात्रिंशत्",
      "latin": "aṣṭātriṁśat",
      "localNames": ["thirty-eight", "38"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 39,
      "audioUrl": "decks/numbers/assets/audio/00000039.mp3",
      "unicode": "नवत्रिंशत्",
      "latin": "navatriṁśat",
      "localNames": ["thirty-nine", "39"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 40,
      "audioUrl": "decks/numbers/assets/audio/00000040-3.mp3",
      "unicode": "चत्वारिंशत्",
      "latin": "catvāriṁśat",
      "localNames": ["forty", "40"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 41,
      "audioUrl": "decks/numbers/assets/audio/00000041.mp3",
      "unicode": "एकचत्वारिंशत्",
      "latin": "ēkacatvāriṁśat",
      "localNames": ["forty-one", "41"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 42,
      "audioUrl": "decks/numbers/assets/audio/00000042.mp3",
      "unicode": "द्विचत्वारिंशत्",
      "latin": "dvicatvāriṁśat",
      "localNames": ["forty-two", "42"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 43,
      "audioUrl": "decks/numbers/assets/audio/00000043.mp3",
      "unicode": "त्रिचत्वारिंशत्",
      "latin": "tricatvāriṁśat",
      "localNames": ["forty-three", "43"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 44,
      "audioUrl": "decks/numbers/assets/audio/00000044.mp3",
      "unicode": "चतुश्चत्वारिंशत्",
      "latin": "catuścatvāriṁśat",
      "localNames": ["forty-four", "44"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 45,
      "audioUrl": "decks/numbers/assets/audio/00000045.mp3",
      "unicode": "पञ्चचत्वारिंशत्",
      "latin": "pañcacatvāriṁśat",
      "localNames": ["forty-five", "45"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 46,
      "audioUrl": "decks/numbers/assets/audio/00000046.mp3",
      "unicode": "षट्चत्वारिंशत्",
      "latin": "ṣaṭcatvāriṁśat",
      "localNames": ["forty-six", "46"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 47,
      "audioUrl": "decks/numbers/assets/audio/00000047.mp3",
      "unicode": "सप्तचत्वारिंशत्",
      "latin": "saptacatvāriṁśat",
      "localNames": ["forty-seven", "47"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 48,
      "audioUrl": "decks/numbers/assets/audio/00000048.mp3",
      "unicode": "अष्टचत्वारिंशत्",
      "latin": "aṣṭacatvāriṁśat",
      "localNames": ["forty-eight", "48"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 49,
      "audioUrl": "decks/numbers/assets/audio/00000049.mp3",
      "unicode": "नवचत्वारिंशत्",
      "latin": "navacatvāriṁśat",
      "localNames": ["forty-nine", "49"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 50,
      "audioUrl": "decks/numbers/assets/audio/00000050-3.mp3",
      "unicode": "पञ्चाशत्",
      "latin": "pañcāśat",
      "localNames": ["fifty", "50"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 51,
      "audioUrl": "decks/numbers/assets/audio/00000051.mp3",
      "unicode": "एकपञ्चाशत्",
      "latin": "ēkapañcāśat",
      "localNames": ["fifty-one", "51"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 52,
      "audioUrl": "decks/numbers/assets/audio/00000052.mp3",
      "unicode": "द्विपञ्च्शत्",
      "latin": "dvipañcāśat",
      "localNames": ["fifty-two", "52"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 53,
      "audioUrl": "decks/numbers/assets/audio/00000053.mp3",
      "unicode": "त्रिपञ्चाशत्",
      "latin": "tripañcāśat",
      "localNames": ["fifty-three", "53"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 54,
      "audioUrl": "decks/numbers/assets/audio/00000054.mp3",
      "unicode": "चतुःपञ्चाशत्",
      "latin": "catuḥpañcāśat",
      "localNames": ["fifty-four", "54"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 55,
      "audioUrl": "decks/numbers/assets/audio/00000055.mp3",
      "unicode": "पञ्चपञ्चाशत्",
      "latin": "pañcapañcāśat",
      "localNames": ["fifty-five", "55"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 56,
      "audioUrl": "decks/numbers/assets/audio/00000056.mp3",
      "unicode": "षट्पञ्चाशत्",
      "latin": "ṣatpañcāśat",
      "localNames": ["fifty-six", "56"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 57,
      "audioUrl": "decks/numbers/assets/audio/00000057.mp3",
      "unicode": "सप्तपञ्चाशत्",
      "latin": "",
      "localNames": ["fifty-seven", "57"],
      "description": "saptapañcāśat",
      "group": "51-100",
    },
    {
      "subjectId": 58,
      "audioUrl": "decks/numbers/assets/audio/00000058.mp3",
      "unicode": "अष्टपञ्चाशत्",
      "latin": "",
      "localNames": ["fifty-eight", "58"],
      "description": "aṣṭapañcāśat",
      "group": "51-100",
    },
    {
      "subjectId": 59,
      "audioUrl": "decks/numbers/assets/audio/00000059.mp3",
      "unicode": "नवपञ्चाशत्",
      "latin": "",
      "localNames": ["fifty-nine", "59"],
      "description": "navapañcāśat",
      "group": "51-100",
    },
    {
      "subjectId": 60,
      "audioUrl": "decks/numbers/assets/audio/00000060-2.mp3",
      "unicode": "षष्टिः",
      "latin": "ṣaṣṭiḥ",
      "localNames": ["sixty", "60"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 61,
      "audioUrl": "decks/numbers/assets/audio/00000061.mp3",
      "unicode": "एकषष्टिः",
      "latin": "ēkaṣaṣṭiḥ",
      "localNames": ["sixty-one", "61"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 62,
      "audioUrl": "decks/numbers/assets/audio/00000062.mp3",
      "unicode": "द्विषष्टिः",
      "latin": "dviṣaṣṭiḥ",
      "localNames": ["sixty-two", "62"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 63,
      "audioUrl": "decks/numbers/assets/audio/00000063.mp3",
      "unicode": "त्रिषष्टिः",
      "latin": "triṣaṣṭiḥ",
      "localNames": ["sixty-three", "63"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 64,
      "audioUrl": "decks/numbers/assets/audio/00000064.mp3",
      "unicode": "चतुःषष्टिः",
      "latin": "catuḥṣaṣṭiḥ",
      "localNames": ["sixty-four", "64"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 65,
      "audioUrl": "decks/numbers/assets/audio/00000065.mp3",
      "unicode": "पङ्चषष्टिः",
      "latin": "pañcaṣaṣṭiḥ",
      "localNames": ["sixty-five", "65"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 66,
      "audioUrl": "decks/numbers/assets/audio/00000066.mp3",
      "unicode": "षट्षष्टिः",
      "latin": "ṣaṭṣaṣṭiḥ",
      "localNames": ["sixty-six", "66"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 67,
      "audioUrl": "decks/numbers/assets/audio/00000067.mp3",
      "unicode": "सप्तषष्टिः",
      "latin": "saptaṣaṣṭiḥ",
      "localNames": ["sixty-seven", "67"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 68,
      "audioUrl": "decks/numbers/assets/audio/00000068.mp3",
      "unicode": "अष्टषष्टिः",
      "latin": "aṣṭaṣaṣṭiḥ",
      "localNames": ["sixty-eight", "68"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 69,
      "audioUrl": "decks/numbers/assets/audio/00000069.mp3",
      "unicode": "नवषष्टिः",
      "latin": "navaṣaṣṭiḥ",
      "localNames": ["sixty-nine", "69"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 70,
      "audioUrl": "decks/numbers/assets/audio/00000070-2.mp3",
      "unicode": "सप्ततिः",
      "latin": "saptatiḥ",
      "localNames": ["seventy", "70"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 71,
      "audioUrl": "decks/numbers/assets/audio/00000071.mp3",
      "unicode": "एकसप्ततिः",
      "latin": "ēkasaptatiḥ",
      "localNames": ["seventy-one", "71"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 72,
      "audioUrl": "decks/numbers/assets/audio/00000072.mp3",
      "unicode": "द्विसप्ततिः",
      "latin": "dvisaptatiḥ",
      "localNames": ["seventy-two", "72"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 73,
      "audioUrl": "decks/numbers/assets/audio/00000073.mp3",
      "unicode": "त्रिसप्ततिः",
      "latin": "trisaptatiḥ",
      "localNames": ["seventy-three", "73"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 74,
      "audioUrl": "decks/numbers/assets/audio/00000074.mp3",
      "unicode": "चतुस्सप्ततिः",
      "latin": "catussaptatiḥ",
      "localNames": ["seventy-four", "74"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 75,
      "audioUrl": "decks/numbers/assets/audio/00000075.mp3",
      "unicode": "पञ्चसप्ततिः",
      "latin": "pañcasaptatiḥ",
      "localNames": ["seventy-five", "75"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 76,
      "audioUrl": "decks/numbers/assets/audio/00000076.mp3",
      "unicode": "षट्सप्ततिः",
      "latin": "ṣaṭsaptatiḥ",
      "localNames": ["seventy-six", "76"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 77,
      "audioUrl": "decks/numbers/assets/audio/00000077.mp3",
      "unicode": "सप्तसप्ततिः",
      "latin": "saptasaptatiḥ",
      "localNames": ["seventy-seven", "77"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 78,
      "audioUrl": "decks/numbers/assets/audio/00000078.mp3",
      "unicode": "अष्टसप्ततिः",
      "latin": "aṣṭasaptatiḥ",
      "localNames": ["seventy-eight", "78"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 79,
      "audioUrl": "decks/numbers/assets/audio/00000079.mp3",
      "unicode": "नवसप्ततिः",
      "latin": "navasaptatiḥ",
      "localNames": ["seventy-nine", "79"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 80,
      "audioUrl": "decks/numbers/assets/audio/00000080-2.mp3",
      "unicode": "अशीतिः",
      "latin": "aśītiḥ",
      "localNames": ["eighty", "80"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 81,
      "audioUrl": "decks/numbers/assets/audio/00000081.mp3",
      "unicode": "एकाशीतिः",
      "latin": "ēkāśītiḥ",
      "localNames": ["eighty-one", "81"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 82,
      "audioUrl": "decks/numbers/assets/audio/00000082.mp3",
      "unicode": "द्व्यशीतिः",
      "latin": "dvyaśītiḥ",
      "localNames": ["eighty-two", "82"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 83,
      "audioUrl": "decks/numbers/assets/audio/00000083.mp3",
      "unicode": "त्र्यशीतिः",
      "latin": "tryaśītiḥ",
      "localNames": ["eighty-three", "83"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 84,
      "audioUrl": "decks/numbers/assets/audio/00000084.mp3",
      "unicode": "चतुरशीतिः",
      "latin": "caturaśītiḥ",
      "localNames": ["eighty-four", "84"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 85,
      "audioUrl": "decks/numbers/assets/audio/00000085.mp3",
      "unicode": "पञ्चाशीतिः",
      "latin": "pañcāśītiḥ",
      "localNames": ["eighty-five", "85"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 86,
      "audioUrl": "decks/numbers/assets/audio/00000086.mp3",
      "unicode": "षडशीतिः",
      "latin": "ṣaḍaśītiḥ",
      "localNames": ["eighty-six", "86"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 87,
      "audioUrl": "decks/numbers/assets/audio/00000087.mp3",
      "unicode": "सप्ताशीतिः",
      "latin": "saptāśītiḥ",
      "localNames": ["eighty-seven", "87"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 88,
      "audioUrl": "decks/numbers/assets/audio/00000088.mp3",
      "unicode": "अष्टाशीतिः",
      "latin": "aṣṭāśītiḥ",
      "localNames": ["eighty-eight", "88"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 89,
      "audioUrl": "decks/numbers/assets/audio/00000089.mp3",
      "unicode": "नवाशीतिः",
      "latin": "navāśītiḥ",
      "localNames": ["eighty-nine", "89"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 90,
      "audioUrl": "decks/numbers/assets/audio/00000090-2.mp3",
      "unicode": "नवतिः",
      "latin": "navatiḥ",
      "localNames": ["ninety", "90"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 91,
      "audioUrl": "decks/numbers/assets/audio/00000091.mp3",
      "unicode": "एकनवतिः",
      "latin": "ēkanavatiḥ",
      "localNames": ["ninety-one", "91"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 92,
      "audioUrl": "decks/numbers/assets/audio/00000092.mp3",
      "unicode": "द्विनवतिः",
      "latin": "dvinavatiḥ",
      "localNames": ["ninety-two", "92"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 93,
      "audioUrl": "decks/numbers/assets/audio/00000093.mp3",
      "unicode": "त्रिनवतिः",
      "latin": "trinavatiḥ",
      "localNames": ["ninety-three", "93"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 94,
      "audioUrl": "decks/numbers/assets/audio/00000094.mp3",
      "unicode": "चतुर्नवतिः",
      "latin": "caturnavatiḥ",
      "localNames": ["ninety-four", "94"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 95,
      "audioUrl": "decks/numbers/assets/audio/00000095.mp3",
      "unicode": "पञ्चनवतिः",
      "latin": "pañcanavatiḥ",
      "localNames": ["ninety-five", "95"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 96,
      "audioUrl": "decks/numbers/assets/audio/00000096.mp3",
      "unicode": "षण्णवतिः",
      "latin": "ṣaṇṇavatiḥ",
      "localNames": ["ninety-six", "96"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 97,
      "audioUrl": "decks/numbers/assets/audio/00000097.mp3",
      "unicode": "सप्तनवतिः",
      "latin": "saptanavatiḥ",
      "localNames": ["ninety-seven", "97"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 98,
      "audioUrl": "decks/numbers/assets/audio/00000098.mp3",
      "unicode": "अष्टनवतिः",
      "latin": "aṣṭanavatiḥ",
      "localNames": ["ninety-eight", "98"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 99,
      "audioUrl": "decks/numbers/assets/audio/00000099.mp3",
      "unicode": "नवनवतिः",
      "latin": "navanavatiḥ",
      "localNames": ["ninety-nine", "99"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 100,
      "audioUrl": "decks/numbers/assets/audio/00000100-4.mp3",
      "unicode": "शतम्",
      "latin": "śatam",
      "localNames": ["one hundred", "100"],
      "description": "",
      "group": "51-100",
    },
    {
      "subjectId": 1000,
      "audioUrl": "decks/numbers/assets/audio/00001000.mp3",
      "unicode": "सहस्रम्",
      "latin": "sahasram",
      "localNames": ["one thousand", "1000"],
      "description": "",
      "group": ">100",
    },
    {
      "subjectId": 100000,
      "audioUrl": "decks/numbers/assets/audio/00100000.mp3",
      "unicode": "लक्षम्",
      "latin": "lakṣam",
      "localNames": ["one hundred thousand", "1,00,000"],
      "description": "",
      "group": ">100",
    },
    {
      "subjectId": 10000000,
      "audioUrl": "decks/numbers/assets/audio/10000000.mp3",
      "unicode": "कोटिः",
      "latin": "koṭiḥ",
      "localNames": ["ten million", "1,00,00,000"],
      "description": "",
      "group": ">100",
    },
  ]
}

var app = Elm.Main.init({
  node: document.getElementById('elm'),
  flags: numbers
});