var numbers = {
  "deckId": "numbers",
  "deckTitle": "Sanskrit Numbers",
  "landingPage": "index.html",
  "initialScript": "Unicode",
  "scriptCanBeSet": true,
  "autoPlayCanBeSet": true,
  "mainPartFontSize": "32pt",
  "showAudioWithUrNameQuiz": false,
  "showAudioWithLocalNameQuiz": true,
  "showDescription": false,
  "groupCanBeSet": true,
  "groupDisplay": "Group",
  "trainingModes": [
    "Review",
    "Urname",
    "LocalName"
  ],
  "pluralSubjectName": "Numbers",
  "copyrightNotice": "",
  "numChoices": 4,
  "trainModeDisplay": {
    "Review": "Review",
    "Urname": "Sanskrit",
    "LocalName": "English",
  },
  "scriptHeading": "Sanskrit Script",
  "allSubjects": [
    {
      "subjectId": 1,
      "audioUrl": "decks/numbers/assets/audio/00000001.mp3",
      "unicode": "एकम्",
      "latin": "ēkam",
      "localNames": ["one", "1"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 2,
      "audioUrl": "decks/numbers/assets/audio/00000002.mp3",
      "unicode": "द्वे",
      "latin": "dvē",
      "localNames": ["two", "2"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 3,
      "audioUrl": "decks/numbers/assets/audio/00000003.mp3",
      "unicode": "त्रीणि",
      "latin": "trīṇi",
      "localNames": ["three", "3"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 4,
      "audioUrl": "decks/numbers/assets/audio/00000004.mp3",
      "unicode": "चत्वारि",
      "latin": "catvāri",
      "localNames": ["four", "4"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 5,
      "audioUrl": "decks/numbers/assets/audio/00000005.mp3",
      "unicode": "पञ्च",
      "latin": "pañca",
      "localNames": ["five", "5"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 6,
      "audioUrl": "decks/numbers/assets/audio/00000006.mp3",
      "unicode": "षट्",
      "latin": "ṣaṭ",
      "localNames": ["six", "6"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 7,
      "audioUrl": "decks/numbers/assets/audio/00000007.mp3",
      "unicode": "सप्त",
      "latin": "sapta",
      "localNames": ["seven", "7"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 8,
      "audioUrl": "decks/numbers/assets/audio/00000008.mp3",
      "unicode": "अष्ट",
      "latin": "aṣṭa",
      "localNames": ["eight", "8"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 9,
      "audioUrl": "decks/numbers/assets/audio/00000009.mp3",
      "unicode": "नव",
      "latin": "nava",
      "localNames": ["nine", "9"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 10,
      "audioUrl": "decks/numbers/assets/audio/00000010.mp3",
      "unicode": "दश",
      "latin": "daśa",
      "localNames": ["ten", "10"],
      "description": "",
      "group": "1-10",
    },
    {
      "subjectId": 11,
      "audioUrl": "decks/numbers/assets/audio/00000011.mp3",
      "unicode": "एकादश",
      "latin": "ēkādaśa",
      "localNames": ["eleven", "11"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 12,
      "audioUrl": "decks/numbers/assets/audio/00000012.mp3",
      "unicode": "द्वादश",
      "latin": "dvādaśa",
      "localNames": ["twelve", "12"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 13,
      "audioUrl": "decks/numbers/assets/audio/00000013.mp3",
      "unicode": "त्रयॊदश",
      "latin": "trayodaśa",
      "localNames": ["thirteen", "13"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 14,
      "audioUrl": "decks/numbers/assets/audio/00000014.mp3",
      "unicode": "चतुर्दश",
      "latin": "caturdaśa",
      "localNames": ["fourteen", "14"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 15,
      "audioUrl": "decks/numbers/assets/audio/00000015.mp3",
      "unicode": "पञ्चदश",
      "latin": "pañcadaśa",
      "localNames": ["fifteen", "15"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 16,
      "audioUrl": "decks/numbers/assets/audio/00000016.mp3",
      "unicode": "षोडश",
      "latin": "ṣōḍaśa",
      "localNames": ["sixteen", "16"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 17,
      "audioUrl": "decks/numbers/assets/audio/00000017.mp3",
      "unicode": "सप्तदश",
      "latin": "saptadaśa",
      "localNames": ["seventeen", "17"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 18,
      "audioUrl": "decks/numbers/assets/audio/00000018.mp3",
      "unicode": "अष्टादश",
      "latin": "aṣṭādaśa",
      "localNames": ["eighteen", "18"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 19,
      "audioUrl": "decks/numbers/assets/audio/00000019.mp3",
      "unicode": "नवदश",
      "latin": "navadaśa",
      "localNames": ["nineteen", "19"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 20,
      "audioUrl": "decks/numbers/assets/audio/00000020-3.mp3",
      "unicode": "विंशतिः",
      "latin": "viṁśatiḥ",
      "localNames": ["twenty", "20"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 21,
      "audioUrl": "decks/numbers/assets/audio/00000021.mp3",
      "unicode": "एकविंशतिः",
      "latin": "ēkaviṁśatiḥ",
      "localNames": ["twenty-one", "21"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 22,
      "audioUrl": "decks/numbers/assets/audio/00000022.mp3",
      "unicode": "द्वाविंशतिः",
      "latin": "dvāviṁśatiḥ",
      "localNames": ["twenty-two", "22"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 23,
      "audioUrl": "decks/numbers/assets/audio/00000023.mp3",
      "unicode": "त्रयोविंशतिः",
      "latin": "trayōviṁśatiḥ",
      "localNames": ["twenty-three", "23"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 24,
      "audioUrl": "decks/numbers/assets/audio/00000024.mp3",
      "unicode": "चतुर्विंशतिः",
      "latin": "caturviṁśatiḥ",
      "localNames": ["twenty-four", "24"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 25,
      "audioUrl": "decks/numbers/assets/audio/00000025.mp3",
      "unicode": "पञ्चविंशतिः",
      "latin": "pañcaviṁśatiḥ",
      "localNames": ["twenty-five", "25"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 26,
      "audioUrl": "decks/numbers/assets/audio/00000026.mp3",
      "unicode": "षड्विंशतिः",
      "latin": "ṣaḍviṁśatiḥ",
      "localNames": ["twenty-six", "26"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 27,
      "audioUrl": "decks/numbers/assets/audio/00000027.mp3",
      "unicode": "सप्तविंशतिः",
      "latin": "saptaviṁśatiḥ",
      "localNames": ["twenty-seven", "27"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 28,
      "audioUrl": "decks/numbers/assets/audio/00000028.mp3",
      "unicode": "अष्टाविंशतिः",
      "latin": "aṣṭāviṁśatiḥ",
      "localNames": ["twenty-eight", "28"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 29,
      "audioUrl": "decks/numbers/assets/audio/00000029.mp3",
      "unicode": "नवविंशतिः",
      "latin": "navaviṁśatiḥ",
      "localNames": ["twenty-nine", "29"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 30,
      "audioUrl": "decks/numbers/assets/audio/00000030-3.mp3",
      "unicode": "त्रिंशत्",
      "latin": "triṁśat",
      "localNames": ["thirty", "30"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 31,
      "audioUrl": "decks/numbers/assets/audio/00000031.mp3",
      "unicode": "एकत्रिंशत्",
      "latin": "ēkatriṁśat",
      "localNames": ["thirty-one", "31"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 32,
      "audioUrl": "decks/numbers/assets/audio/00000032.mp3",
      "unicode": "द्वात्रिंशत्",
      "latin": "dvātriṁśat",
      "localNames": ["thirty-two", "32"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 33,
      "audioUrl": "decks/numbers/assets/audio/00000033.mp3",
      "unicode": "त्रयस्त्रिंशत्",
      "latin": "trayastriṁśat",
      "localNames": ["thirty-three", "33"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 34,
      "audioUrl": "decks/numbers/assets/audio/00000034.mp3",
      "unicode": "चतुस्त्रिंशत्",
      "latin": "catustriṁśat",
      "localNames": ["thirty-four", "34"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 35,
      "audioUrl": "decks/numbers/assets/audio/00000035.mp3",
      "unicode": "पञ्चत्रिंशत्",
      "latin": "pañcatriṁśat",
      "localNames": ["thirty-five", "35"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 36,
      "audioUrl": "decks/numbers/assets/audio/00000036.mp3",
      "unicode": "षट्त्रिंशत्",
      "latin": "ṣaṭtriṁśat",
      "localNames": ["thirty-six", "36"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 37,
      "audioUrl": "decks/numbers/assets/audio/00000037.mp3",
      "unicode": "सप्तत्रिंशत्",
      "latin": "saptatriṁśat",
      "localNames": ["thirty-seven", "37"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 38,
      "audioUrl": "decks/numbers/assets/audio/00000038.mp3",
      "unicode": "अष्टात्रिंशत्",
      "latin": "aṣṭātriṁśat",
      "localNames": ["thirty-eight", "38"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 39,
      "audioUrl": "decks/numbers/assets/audio/00000039.mp3",
      "unicode": "नवत्रिंशत्",
      "latin": "navatriṁśat",
      "localNames": ["thirty-nine", "39"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 40,
      "audioUrl": "decks/numbers/assets/audio/00000040-3.mp3",
      "unicode": "चत्वारिंशत्",
      "latin": "catvāriṁśat",
      "localNames": ["forty", "40"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 41,
      "audioUrl": "decks/numbers/assets/audio/00000041.mp3",
      "unicode": "एकचत्वारिंशत्",
      "latin": "ēkacatvāriṁśat",
      "localNames": ["forty-one", "41"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 42,
      "audioUrl": "decks/numbers/assets/audio/00000042.mp3",
      "unicode": "द्विचत्वारिंशत्",
      "latin": "dvicatvāriṁśat",
      "localNames": ["forty-two", "42"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 43,
      "audioUrl": "decks/numbers/assets/audio/00000043.mp3",
      "unicode": "त्रिचत्वारिंशत्",
      "latin": "tricatvāriṁśat",
      "localNames": ["forty-three", "43"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 44,
      "audioUrl": "decks/numbers/assets/audio/00000044.mp3",
      "unicode": "चतुश्चत्वारिंशत्",
      "latin": "catuścatvāriṁśat",
      "localNames": ["forty-four", "44"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 45,
      "audioUrl": "decks/numbers/assets/audio/00000045.mp3",
      "unicode": "पञ्चचत्वारिंशत्",
      "latin": "pañcacatvāriṁśat",
      "localNames": ["forty-five", "45"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 46,
      "audioUrl": "decks/numbers/assets/audio/00000046.mp3",
      "unicode": "षट्चत्वारिंशत्",
      "latin": "ṣaṭcatvāriṁśat",
      "localNames": ["forty-six", "46"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 47,
      "audioUrl": "decks/numbers/assets/audio/00000047.mp3",
      "unicode": "सप्तचत्वारिंशत्",
      "latin": "saptacatvāriṁśat",
      "localNames": ["forty-seven", "47"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 48,
      "audioUrl": "decks/numbers/assets/audio/00000048.mp3",
      "unicode": "अष्टचत्वारिंशत्",
      "latin": "aṣṭacatvāriṁśat",
      "localNames": ["forty-eight", "48"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 49,
      "audioUrl": "decks/numbers/assets/audio/00000049.mp3",
      "unicode": "नवचत्वारिंशत्",
      "latin": "navacatvāriṁśat",
      "localNames": ["forty-nine", "49"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 50,
      "audioUrl": "decks/numbers/assets/audio/00000050-3.mp3",
      "unicode": "पञ्चाशत्",
      "latin": "pañcāśat",
      "localNames": ["fifty", "50"],
      "description": "",
      "group": "11-50",
    },
    {
      "subjectId": 60,
      "audioUrl": "decks/numbers/assets/audio/00000060-2.mp3",
      "unicode": "षष्टिः",
      "latin": "ṣaṣṭiḥ",
      "localNames": ["sixty", "60"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 70,
      "audioUrl": "decks/numbers/assets/audio/00000070-2.mp3",
      "unicode": "सप्ततिः",
      "latin": "saptatiḥ",
      "localNames": ["seventy", "70"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 80,
      "audioUrl": "decks/numbers/assets/audio/00000080-2.mp3",
      "unicode": "अशीतिः",
      "latin": "aśītiḥ",
      "localNames": ["eighty", "80"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 90,
      "audioUrl": "decks/numbers/assets/audio/00000090-2.mp3",
      "unicode": "नवतिः",
      "latin": "navatiḥ",
      "localNames": ["ninety", "90"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 100,
      "audioUrl": "decks/numbers/assets/audio/00000100-4.mp3",
      "unicode": "शतम्",
      "latin": "śatam",
      "localNames": ["one hundred", "100"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 1000,
      "audioUrl": "decks/numbers/assets/audio/00001000.mp3",
      "unicode": "सहस्रम्",
      "latin": "sahasram",
      "localNames": ["one thousand", "1000"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 100000,
      "audioUrl": "decks/numbers/assets/audio/00100000.mp3",
      "unicode": "लक्षम्",
      "latin": "lakṣam",
      "localNames": ["one hundred thousand", "1,00,000"],
      "description": "",
      "group": ">50",
    },
    {
      "subjectId": 10000000,
      "audioUrl": "decks/numbers/assets/audio/10000000.mp3",
      "unicode": "कोटिः",
      "latin": "koṭiḥ",
      "localNames": ["ten million", "1,00,00,000"],
      "description": "",
      "group": ">50",
    },
  ]
}

var app = Elm.Main.init({
  node: document.getElementById('elm'),
  flags: numbers
});